config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :content, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :text, presence: true, unless: :was_attached?
  validates :hashtag, presence: true


  def was_attached?
    self.image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  
  has_many :tweets
  has_many :comennts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  before_action :authenticate_user!

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @tweet = Tweet.find(params[:tweet_id])
    if @comment.save
      CommentChannel.broadcast_to @tweet, { comment: @comment, user: @comment.user }
    else
      @tweet = @comment.tweet
      @comments = @tweet.comments
      render "tweets/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, tweet_id: params[:tweet_id] )
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :show]

  def index
    @tweet = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    if @tweet.user_id != current_user.id 
      redirect_to root_path
   end
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweet_path
    else
      render :edit
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :text, :hashtag, :image).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>memory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
          <h1>memory</h1>
            <%#<%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
            <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "投稿", new_tweet_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with model: tweet, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :text, "本文" %><br />
    <%= f.text_area :text, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :hashtag, "#" %><br />
    <%= f.text_area :hashtag, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :iamge, "画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="card">
  <%= link_to image_tag(tweet.image, class: :card__img ), tweet_path(tweet.id)if tweet.image.attached? %>
  <div class="card__body">
    <%= link_to tweet.title, tweet_path(tweet.id), class: :card__title%>
    <p class="card__summary">
      <%= tweet.hashtag %>
    </p>
    <%= link_to "by #{tweet.user.nickname}", tweet_path(tweet.user.id), class: :card__user %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { tweet: @tweet} %>
    </div>
  </div>
</div>

app/views/tweets/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
      <%# <div class="greeting"> %>
        <%# こんにちは、 %>
        <%# <%= link_to "ユーザー名さん", root_path, class: :greeting__link%>
      <%# </div> %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: 'tweet', collection: @tweet %>
    </div>
  </div>
</main>

app/views/tweets/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { tweet: @tweet} %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @tweet.title %>
      </p>
      <%= link_to "by #{@tweet.user.nickname}", root_path, class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
          <%= link_to "編集した", edit_tweet_path(@tweet.id), class: :prototype__btn %>
          <%= link_to "削除する", tweet_path(@tweet.id), method: :delete, class: :prototype__btn %>
        </div>
        <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <% if @tweet.image.attached? %>
          <%= image_tag @tweet.image %> 
        <% end %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">タイトル</p>
          <p class="detail__message">
            <%= @tweet.title %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">本文</p>
          <p class="detail__message">
            <%= @tweet.text %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">#</p>
          <p class="detail__message">
            <%= @tweet.hashtag %>
        </div>
      </div>
      
      <div id="comments">
      <h4>＜コメント一覧＞</h4>
        <% @tweet.comments.each do |comment| %>
          <div class="comment">
            <p class="user-info"><%= comment.user.nickname %>： </p>
            <p><%= comment.content %></p>
            <% if user_signed_in? && current_user.id == comment.user_id %>
            <%#<p><%=link_to "削除", item_comment_path(comment.item.id), method: :delete, class: "comment-destroy" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  
    <% if user_signed_in? %>
    <div class="comment-box">
      <%= form_with model: [@tweet, @comment], id: "comment-form" do |f| %>
        <%= f.text_area :content , class: "comment-text"%>
      <button type="submit" class="comment-btn">
        <%= f.submit "コメントをする", class: "comment-submit" %>
      </button>
    <% end %>
  </div>
  <% end %> 
    </div>
  </div>
</main>